In [1]:
import numpy as np

## Creating matrix using numpy

In [2]:
m1 = np.array([[2,3],[6,7]])
print(m1)

[[2 3]
 [6 7]]


In [3]:
m1.shape

(2, 2)

In [4]:
m2 = np.array([[89,90,47],[44,55,66],[67,78,89]])
print(m2)

[[89 90 47]
 [44 55 66]
 [67 78 89]]


In [5]:
m2.shape

(3, 3)

## creating matrices with random values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.8689377  0.68769675 0.20868365]
 [0.75226904 0.33420521 0.83472292]
 [0.80553743 0.51771401 0.6652295 ]]


## 
creating matrix with random integers

In [7]:
random_integer_matrix = np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[77 92 23 42 52]
 [82  2 99 12 39]
 [71 88 79  4 65]
 [95 96 83 98 11]]


## Matrix with all the values ones

In [8]:
matrix_ones = np.ones((2,2))
print(matrix_ones)

[[1. 1.]
 [1. 1.]]


In [9]:
matrix_ones = np.ones((2,2),dtype = int)
print(matrix_ones)

[[1 1]
 [1 1]]


## Null matrix or zero matris

In [10]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
null_matrix = np.zeros((4,4),dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## identity matrix

In [12]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Transpose matrix

In [13]:
a = np.random.randint(100,size=(3,3))
print(a)

[[44 99 58]
 [65 93 26]
 [78 11 69]]


In [14]:
transpose_a = np.transpose(a)
print(transpose_a)

[[44 65 78]
 [99 93 11]
 [58 26 69]]


## Matrix addition

Two matrices added only if they have same shape

In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,2],[7,9]])

In [17]:
print("A : ",A)
print("B : ",B)

A :  [[1 2]
 [3 4]]
B :  [[3 2]
 [7 9]]


In [18]:
A.shape

(2, 2)

In [19]:
B.shape

(2, 2)

In [20]:
print("Sum of matrices :",(A+B))

Sum of matrices : [[ 4  4]
 [10 13]]


## Create Matrices with random variables

In [22]:
matrix1 = np.random.randint(10,size = (3,3))
matrix2 = np.random.randint(10,size = (3,3))

In [23]:
print(matrix1)

[[1 6 6]
 [9 9 3]
 [0 7 8]]


In [24]:
print(matrix2)

[[9 4 4]
 [3 9 8]
 [4 3 4]]


In [25]:
sum = np.add(matrix1,matrix2)
print(sum)

[[10 10 10]
 [12 18 11]
 [ 4 10 12]]


In [26]:
matrix1 = np.random.randint(10,size = (3,3))
matrix2 = np.random.randint(10,size = (3,4))

In [27]:
sum2 = np.add(matrix1,matrix2)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

## we get this error because shape of two matrices have different shape


## Matrix subtraction

In [28]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,2],[7,9]])
difference = A - B
print(difference)

[[-2  0]
 [-4 -5]]


In [29]:
matrix1 = np.random.randint(10,size = (3,3))
matrix2 = np.random.randint(10,size = (3,3))
print("Matrix 1 : ",matrix1)
print("Matrix 2 : ",matrix2)
diff = matrix1 - matrix2
print("Difference  :", diff)

Matrix 1 :  [[5 0 6]
 [0 7 5]
 [9 6 0]]
Matrix 2 :  [[9 6 7]
 [2 6 2]
 [9 8 1]]
Difference  : [[-4 -6 -1]
 [-2  1  3]
 [ 0 -2 -1]]


## Multipy matrix by a scalar value

In [36]:
x = 4
y = np.random.randint(10,size = (3,3))
t = np.multiply(x,y)
print("X : ",y)
print("Answer " ,t)

X :  [[5 3 2]
 [9 3 6]
 [8 1 8]]
Answer  [[20 12  8]
 [36 12 24]
 [32  4 32]]


## Multiplication ot two matrices

In [39]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,2],[7,9]])
ans = np.dot(A,B)
print("Answer  : ", ans)

Answer  :  [[17 20]
 [37 42]]


In [40]:
matrix1 = np.random.randint(10,size = (3,3))
matrix2 = np.random.randint(10,size = (3,3))
print("Matrix 1 : ",matrix1)
print("Matrix 2 : ",matrix2)
prod = np.dot(matrix1,matrix2)
print("product :",prod)

Matrix 1 :  [[4 9 8]
 [7 7 6]
 [5 9 8]]
Matrix 2 :  [[5 6 5]
 [2 0 2]
 [6 6 6]]
product : [[86 72 86]
 [85 78 85]
 [91 78 91]]


In [41]:
matrix1 = np.random.randint(10,size = (3,3))
matrix2 = np.random.randint(10,size = (4,3))
print("Matrix 1 : ",matrix1)
print("Matrix 2 : ",matrix2)
prod = np.dot(matrix1,matrix2)
print("product :",prod)

Matrix 1 :  [[9 4 0]
 [4 5 4]
 [8 1 0]]
Matrix 2 :  [[7 0 1]
 [2 6 8]
 [7 7 6]
 [6 8 5]]


ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

## In multiplication m1 column is same as m2 row

## Element multiplication

In [43]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,2],[7,9]])
ans = np.multiply(A,B)
print("Answer  : ", ans)

Answer  :  [[ 3  4]
 [21 36]]
